export const GLOBAL_DASHBOARD_SIDEBAR_OPEN = 'GLOBAL_DASHBOARD_SIDEBAR_OPEN';
export const GLOBAL_GENERAL_SPINNER = 'GLOBAL_GENERAL_SPINNER';
export const GLOBAL_COUNTRIES_OPTIONS = 'GLOBAL_COUNTRIES_OPTIONS';
export const GLOBAL_DEPARTMENTS_OPTIONS = 'GLOBAL_DEPARTMENTS_OPTIONS';
export const GLOBAL_CITIES_OPTIONS = 'GLOBAL_CITIES_OPTIONS';
