export const USER_NAME = 'USER_NAME';
export const USER_LASTNAME = 'USER_LASTNAME';
export const USER_DATA = 'USER_DATA';
export const USER_PAYSTATUSES = 'USER_PAYSTATUSES';
export const USER_SELECTED_COUNTRY = 'USER_SELECTED_COUNTRY';
export const USER_SELECTED_DEPARTMENT = 'USER_SELECTED_DEPARTMENT';
export const USER_SELECTED_CITY = 'USER_SELECTED_CITY';
