export const CLEAN_REGISTER = 'CLEAN_REGISTER';
export const REGISTER_NAME = 'REGISTER_NAME';
export const REGISTER_LASTNAME = 'REGISTER_LASTNAME';
export const REGISTER_EMAIL = 'REGISTER_EMAIL';
export const REGISTER_CONFIRM_EMAIL = 'REGISTER_CONFIRM_EMAIL';
export const REGISTER_PASSWORD = 'REGISTER_PASSWORD';
export const REGISTER_CONFIRM_PASSWORD = 'REGISTER_CONFIRM_PASSWORD';
export const REGISTER_DEPARTMENT = 'REGISTER_DEPARTMENT';
export const REGISTER_CITY = 'REGISTER_CITY';
export const REGISTER_ADDRESS = 'REGISTER_ADDRESS';
export const REGISTER_CELLPHONE = 'REGISTER_CELLPHONE';
export const REGISTER_DATA_PROCESSING_POLICY =
  'REGISTER_DATA_PROCESSING_POLICY';
export const REGISTER_ERROR = 'REGISTER_ERROR';
export const REGISTER_PASSWORD_VALIDATE = 'REGISTER_PASSWORD_VALIDATE';
